/** Sets a new selected lamp type */
export const SET_SELECTED_LAMP_TYPE = 'SET_SELECTED_LAMP_TYPE';
export const SET_SELECTED_SKY_TYPE = 'SET_SELECTED_SKY_TYPE';
export const SET_GRADATION_INFLECTION_POINT = 'SET_GRADATION_INFLECTION_POINT';
